### ISSUE TITLE
Suggestion: Town symbols instead of only having red lines.

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Pl3xMap-Towny#1]
Basically, that will make them smaller and bigger towns more visible on the map since they will have a town icon, that icon could be taken from the original dynmap-towny.

**Comment by granny** [comment]
@silverwolfg11 has taken over the development of Pl3xMap-Towny. (Sorry silver for the multiple spam mentions)
https://github.com/silverwolfg11/Pl3xMap-Towny

Attempt to reproduce using their version of the addon. Leave an issue on their repo if this feature has not been implemented.
