### ISSUE TITLE
Bug: Town claims are triangular and very off

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Pl3xMap-Towny#2]
As seen on this screenshot, the towns have very weird and bugged claims: 
![image](https://user-images.githubusercontent.com/33335971/110360305-d97b5b80-803e-11eb-93b6-b013292c254b.png)

**Comment by granny** [comment]
@silverwolfg11 has taken over the development of Pl3xMap-Towny.
https://github.com/silverwolfg11/Pl3xMap-Towny

Attempt to reproduce using their version of the addon. Leave an issue on their repo if this issue continues to happen.
