### ISSUE TITLE
Suggestion: More placeholders + being able to change the nation placeholder saying _none_

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Pl3xMap-Towny#3]
Basically, it would be cool to have a way to modify the _none_ to only none for the nation placeholder and also having a lot of new placeholders like on the original dynmap-towny. (https://github.com/TownyAdvanced/Dynmap-Towny/wiki).

**Comment by granny** [comment]
@silverwolfg11 has taken over the development of Pl3xMap-Towny.
https://github.com/silverwolfg11/Pl3xMap-Towny

Attempt to reproduce using their version of the addon. Leave an issue on their repo if this feature has not been implemented.
