### ISSUE TITLE
Suggestion: Nation colors for the claims.

### ISSUE THREAD

**Issue by Agaloth** [pl3xgaming/Pl3xMap-Towny#4]
Basically, it would be cool to have a command in-game like /n set color {red, blue, yellow, green, etc...} where nations can set their nation colors with some preset colors.

**Comment by granny** [comment]
@silverwolfg11 has taken over the development of Pl3xMap-Towny.
https://github.com/silverwolfg11/Pl3xMap-Towny

Attempt to reproduce using their version of the addon. Leave an issue on their repo if this feature has not been implemented.
