### ISSUE TITLE
Town plots displays in all worlds

### ISSUE THREAD

**Issue by honnisha** [pl3xgaming/Pl3xMap-Towny#7]
For example I have town in world and its displayed correctrly. All regions from world displays also in world_rpg.

**Comment by granny** [comment]
@silverwolfg11 has taken over the development of Pl3xMap-Towny.
https://github.com/silverwolfg11/Pl3xMap-Towny

Attempt to reproduce using their version of the addon. Leave an issue on their repo if this issue continues to happen.
